language: node_js
node_js:
  - "node"

before_script:
  - cd api && npm install && cd ..
  - cd app && npm install && cd ..
  - npm install -g standard

script:
  - cd api && standard && cd ..
  - cd app && standard && cd ..
